version: '3.10'

services:
  poke_django:
    build: .
    container_name: poke_django
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/usr/src/app
    ports:
      - '8001:8001'
    depends_on:
      - pokedb

  pokedb:
    image: postgres
    ports:
      - '8001:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pokemon_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    container_name: pokedb

volumes:
  pgdata:
