# Generated by Django 4.1.1 on 2022-09-17 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemon', '0003_alter_pokemon_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='owner',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='owners',
            field=models.ManyToManyField(related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
