# Generated by Django 4.1.1 on 2022-09-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_remove_pokemon_owner_pokemon_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
